//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xwx.TDP.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xwx.TDP.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap discard {
            get {
                object obj = ResourceManager.GetObject("discard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap edit1 {
            get {
                object obj = ResourceManager.GetObject("edit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap FolderClosed {
            get {
                object obj = ResourceManager.GetObject("FolderClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap FolderOpened {
            get {
                object obj = ResourceManager.GetObject("FolderOpened", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Graph {
            get {
                object obj = ResourceManager.GetObject("Graph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap limits {
            get {
                object obj = ResourceManager.GetObject("limits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Corrupted data file 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Common_CorruptedDataFile {
            get {
                return ResourceManager.GetString("LNG_TDP_Common_CorruptedDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Common_Error {
            get {
                return ResourceManager.GetString("LNG_TDP_Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EngineMode 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_EngineMode {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_EngineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_ExecutionStatus_Error {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_ExecutionStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executed 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_ExecutionStatus_Executed {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_ExecutionStatus_Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_ExecutionStatus_Failed {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_ExecutionStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_ExecutionStatus_OK {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_ExecutionStatus_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passed 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_ExecutionStatus_Passed {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_ExecutionStatus_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skipped 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_ExecutionStatus_Skipped {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_ExecutionStatus_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is a failed test result ouput.
        ///
        ///Click &quot;OK&quot; to continue testing. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_MainLogView_PromptForFailTestMessage {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_MainLogView_PromptForFailTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_Pause {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_Resume {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_Start {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_Stop {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load test sequence failed. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_TdpTestSequence_LoadSequenceFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TdpTestSequence_LoadSequenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save TDP test sequence failed. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_TdpTestSequence_SaveSequenceFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TdpTestSequence_SaveSequenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create case instance failed: 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_TestCase_CreateCaseInstanceFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_CreateCaseInstanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get case limits error. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_TestCase_GetLimitsError {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_GetLimitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get case parameters error. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_TestCase_GetParametersError {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_GetParametersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set case limits error. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_TestCase_SetCaseLimitsError {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_SetCaseLimitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set case parameters error. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_TestCase_SetCaseParametersError {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_SetCaseParametersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TDP library file not found: 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_TestCase_TdplNotFound {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_TdplNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current TDP L version({0}) not compitible with the test case({1}).
        ///TSPL: {2}
        ///Case: {3}
        ///
        ///To ensure the conformance, you must re-create the sequence and configurate the parameters / limits. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_Engine_TestCase_VersionNotCompitiableWarning {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_VersionNotCompitiableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load sequence failed 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_MainLogView_LoadSequenceFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_MainLogView_LoadSequenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the test result folder. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_MainLogView_ResultFolderNotifier {
            get {
                return ResourceManager.GetString("LNG_TDP_MainLogView_ResultFolderNotifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Sequence 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_MainLogView_SelectSequence {
            get {
                return ResourceManager.GetString("LNG_TDP_MainLogView_SelectSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are warnings while loading sequence.
        ///The reason is that some case&apos;s parameter(s) or limit(s) has been removed.
        ///
        ///Before running this sequence, you should go to sequence editor to double-check the changes and re-save it. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_MainLogView_SequenceParameterLimitChangedWarning {
            get {
                return ResourceManager.GetString("LNG_TDP_MainLogView_SequenceParameterLimitChangedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to stop the test? 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_MainLogView_StopConfirm {
            get {
                return ResourceManager.GetString("LNG_TDP_MainLogView_StopConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence Executor 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_MainLogView_Title {
            get {
                return ResourceManager.GetString("LNG_TDP_MainLogView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Value 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceEditor_DefaultValue {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceEditor_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete the selected cases? 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceEditor_DeleteWarning {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceEditor_DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to discard the changes to the sequence? 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceEditor_DiscardWarning {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceEditor_DiscardWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert sequence failed. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceEditor_InsertSequenceFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceEditor_InsertSequenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Sequence Loaded 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceEditor_NoSequenceLoaded {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceEditor_NoSequenceLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save sequence failed. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceEditor_SaveFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceEditor_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence has been modified, do you wan to save the changes? 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceEditor_SavePromptMessage {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceEditor_SavePromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence saved successfully. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceEditor_SaveSuccessfully {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceEditor_SaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value Range 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceEditor_ValueRange {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceEditor_ValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In sequence &quot;{0}&quot;, one or more case&apos;s parameter(s) or limit(s) has been removed.
        ///Please double-check the changes, and re-save the sequence.
        ///
        ///Click &quot;OK&quot; to continue editing the sequence. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceEditor_VersionNotMatchedWarning1 {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceEditor_VersionNotMatchedWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In sequence &quot;{0}&quot;, one or more case&apos;s parameter(s) or limit(s) has been removed.
        ///You should double-check the changes before you save the sequence &quot;{1}&quot;.
        ///
        ///Click &quot;OK&quot; to continue the operation. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceEditor_VersionNotMatchedWarning2 {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceEditor_VersionNotMatchedWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name of the folder to be created: 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_CreatedFolderName {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_CreatedFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create folder failed: 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_CreateFolderFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_CreateFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occured while creating test sequence. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_CreateSequenceFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_CreateSequenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete all the test sequences in the following folder? 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_DeleteFolderConfirm {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_DeleteFolderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete folder failed: 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_DeleteFolderFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_DeleteFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete the following test sequence? 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_DeleteSequenceConfirm {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_DeleteSequenceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The folder can not be renamed now, because the following test sequence is in edit: 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_FolderCanNotBeDeletedWhileSequenceInEdit {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_FolderCanNotBeDeletedWhileSequenceInEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occured while modifing test sequence. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_ModifySequenceFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_ModifySequenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename folder failed: 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_RenamedFolderFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_RenamedFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The new name of the folder: 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_RenamedFolderName {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_RenamedFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The sequence is now running, you can not delete it. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_SequenceCanNotDeleteWhileRunning {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_SequenceCanNotDeleteWhileRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test sequence has existed, please choose another name. 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_SequenceExistedWarning {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_SequenceExistedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File:/t/t{0}
        ///Name:/t/t{1}
        ///----------------------------------------------------------------
        ///
        ///Author:/t/t{2}
        ///Created:/t/t{3}
        ///Modified:/t/t{4}
        ///
        ///Exection Mode
        ///Error:/t/t{5}({6})
        ///OK:/t/t{7}({8})
        ///
        ///Description:
        ///{9} 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_SequenceInfo {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_SequenceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File:/t/t{0}
        ///Name:/t/t{1}
        ///----------------------------------------------------------------
        ///
        ///Author:/t/t{2}
        ///Created:/t{3}
        ///Modified:/t{4}
        ///
        ///Exection Mode
        ///Error:/t/t{5}({6})
        ///OK:/t/t{7}({8})
        ///
        ///Description:
        ///{9} 的本地化字符串。
        /// </summary>
        public static string LNG_TDP_SequenceSelector_SequenceInfo_MenuItem {
            get {
                return ResourceManager.GetString("LNG_TDP_SequenceSelector_SequenceInfo_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap modify {
            get {
                object obj = ResourceManager.GetObject("modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap newfile {
            get {
                object obj = ResourceManager.GetObject("newfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap newFolder {
            get {
                object obj = ResourceManager.GetObject("newFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap parameter {
            get {
                object obj = ResourceManager.GetObject("parameter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap refresh1 {
            get {
                object obj = ResourceManager.GetObject("refresh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap resume {
            get {
                object obj = ResourceManager.GetObject("resume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Sequence {
            get {
                object obj = ResourceManager.GetObject("Sequence", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap showbelow {
            get {
                object obj = ResourceManager.GetObject("showbelow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Test Develop Platform  V0.009 的本地化字符串。
        /// </summary>
        public static string TDP_MainForm_text {
            get {
                return ResourceManager.GetString("TDP_MainForm_text", resourceCulture);
            }
        }
    }
}
