//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xwx.TDP.Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("applications")]
        public string Internal_ApplicationFolder {
            get {
                return ((string)(this["Internal_ApplicationFolder"]));
            }
            set {
                this["Internal_ApplicationFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection Engine_Libraries_DisabledLibrariesAbstractPath {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Engine_Libraries_DisabledLibrariesAbstractPath"]));
            }
            set {
                this["Engine_Libraries_DisabledLibrariesAbstractPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CaseLibrary_TreeView_LastBrowsedFullPath {
            get {
                return ((string)(this["CaseLibrary_TreeView_LastBrowsedFullPath"]));
            }
            set {
                this["CaseLibrary_TreeView_LastBrowsedFullPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CaseLibrary_ApplicationButton_IsShowText {
            get {
                return ((bool)(this["CaseLibrary_ApplicationButton_IsShowText"]));
            }
            set {
                this["CaseLibrary_ApplicationButton_IsShowText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 8.25pt")]
        public global::System.Drawing.Font UI_DefaultFont {
            get {
                return ((global::System.Drawing.Font)(this["UI_DefaultFont"]));
            }
            set {
                this["UI_DefaultFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("320")]
        public int TDP_SequenceLibrary_InfoWindowHeigh {
            get {
                return ((int)(this["TDP_SequenceLibrary_InfoWindowHeigh"]));
            }
            set {
                this["TDP_SequenceLibrary_InfoWindowHeigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int TDP_SequenceEditor_InfoWindowHeigh {
            get {
                return ((int)(this["TDP_SequenceEditor_InfoWindowHeigh"]));
            }
            set {
                this["TDP_SequenceEditor_InfoWindowHeigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection TDP_Engine_Libraries_DisabledLibrariesAbstractPath {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TDP_Engine_Libraries_DisabledLibrariesAbstractPath"]));
            }
            set {
                this["TDP_Engine_Libraries_DisabledLibrariesAbstractPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int TDP_CaseLibrary_InfoWindowHeigh {
            get {
                return ((int)(this["TDP_CaseLibrary_InfoWindowHeigh"]));
            }
            set {
                this["TDP_CaseLibrary_InfoWindowHeigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection TDP_Engine_DisabledLogViewTypeFullName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TDP_Engine_DisabledLogViewTypeFullName"]));
            }
            set {
                this["TDP_Engine_DisabledLogViewTypeFullName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TDP_UI_Language {
            get {
                return ((string)(this["TDP_UI_Language"]));
            }
            set {
                this["TDP_UI_Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_UI_LogView_MainLogViewEngineLogLogView_AutoSctroll {
            get {
                return ((bool)(this["TDP_UI_LogView_MainLogViewEngineLogLogView_AutoSctroll"]));
            }
            set {
                this["TDP_UI_LogView_MainLogViewEngineLogLogView_AutoSctroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 8.25pt")]
        public global::System.Drawing.Font TDP_UI_DefaultFont {
            get {
                return ((global::System.Drawing.Font)(this["TDP_UI_DefaultFont"]));
            }
            set {
                this["TDP_UI_DefaultFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\AutoTest\\Results")]
        public string TDP_TestResultFolder {
            get {
                return ((string)(this["TDP_TestResultFolder"]));
            }
            set {
                this["TDP_TestResultFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TDP_SequenceExecutor_HeaderWidth {
            get {
                return ((string)(this["TDP_SequenceExecutor_HeaderWidth"]));
            }
            set {
                this["TDP_SequenceExecutor_HeaderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360, 360")]
        public global::System.Drawing.Size TDP_MainLogView_GraphFormSize {
            get {
                return ((global::System.Drawing.Size)(this["TDP_MainLogView_GraphFormSize"]));
            }
            set {
                this["TDP_MainLogView_GraphFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TDP_MainLogView_SequenceInfoAreaHeight {
            get {
                return ((int)(this["TDP_MainLogView_SequenceInfoAreaHeight"]));
            }
            set {
                this["TDP_MainLogView_SequenceInfoAreaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name")]
        public string TDP_MainLogView_SequenceInfoDisplayStyle {
            get {
                return ((string)(this["TDP_MainLogView_SequenceInfoDisplayStyle"]));
            }
            set {
                this["TDP_MainLogView_SequenceInfoDisplayStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 14.25pt, style=Bold")]
        public global::System.Drawing.Font TDP_MainLogView_SequenceInfoTextFont {
            get {
                return ((global::System.Drawing.Font)(this["TDP_MainLogView_SequenceInfoTextFont"]));
            }
            set {
                this["TDP_MainLogView_SequenceInfoTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_MainLogView_ShowSequenceInfo {
            get {
                return ((bool)(this["TDP_MainLogView_ShowSequenceInfo"]));
            }
            set {
                this["TDP_MainLogView_ShowSequenceInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("580, 280")]
        public global::System.Drawing.Size TDP_MainLogView_TableFormSize {
            get {
                return ((global::System.Drawing.Size)(this["TDP_MainLogView_TableFormSize"]));
            }
            set {
                this["TDP_MainLogView_TableFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("320, 600")]
        public global::System.Drawing.Size TDP_MainLogView_TreeFormSize {
            get {
                return ((global::System.Drawing.Size)(this["TDP_MainLogView_TreeFormSize"]));
            }
            set {
                this["TDP_MainLogView_TreeFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%d %t %s %e %p")]
        public string TDP_RawDataLogView_ReportFileNamePattern {
            get {
                return ((string)(this["TDP_RawDataLogView_ReportFileNamePattern"]));
            }
            set {
                this["TDP_RawDataLogView_ReportFileNamePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_Engine_MainLogView_LogEngineStatus {
            get {
                return ((bool)(this["TDP_Engine_MainLogView_LogEngineStatus"]));
            }
            set {
                this["TDP_Engine_MainLogView_LogEngineStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_Engine_MainLogView_LogInfo {
            get {
                return ((bool)(this["TDP_Engine_MainLogView_LogInfo"]));
            }
            set {
                this["TDP_Engine_MainLogView_LogInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_Engine_MainLogView_LogInfo_Error {
            get {
                return ((bool)(this["TDP_Engine_MainLogView_LogInfo_Error"]));
            }
            set {
                this["TDP_Engine_MainLogView_LogInfo_Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_Engine_MainLogView_LogInfo_Log {
            get {
                return ((bool)(this["TDP_Engine_MainLogView_LogInfo_Log"]));
            }
            set {
                this["TDP_Engine_MainLogView_LogInfo_Log"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_Engine_MainLogView_LogInfo_Normal {
            get {
                return ((bool)(this["TDP_Engine_MainLogView_LogInfo_Normal"]));
            }
            set {
                this["TDP_Engine_MainLogView_LogInfo_Normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_Engine_MainLogView_LogInfo_Notify {
            get {
                return ((bool)(this["TDP_Engine_MainLogView_LogInfo_Notify"]));
            }
            set {
                this["TDP_Engine_MainLogView_LogInfo_Notify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_Engine_MainLogView_LogInfo_Warning {
            get {
                return ((bool)(this["TDP_Engine_MainLogView_LogInfo_Warning"]));
            }
            set {
                this["TDP_Engine_MainLogView_LogInfo_Warning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_Engine_MainLogView_LogResult {
            get {
                return ((bool)(this["TDP_Engine_MainLogView_LogResult"]));
            }
            set {
                this["TDP_Engine_MainLogView_LogResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_Engine_MainLogView_LogResult_Normal {
            get {
                return ((bool)(this["TDP_Engine_MainLogView_LogResult_Normal"]));
            }
            set {
                this["TDP_Engine_MainLogView_LogResult_Normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_Engine_MainLogView_LogResult_Temp {
            get {
                return ((bool)(this["TDP_Engine_MainLogView_LogResult_Temp"]));
            }
            set {
                this["TDP_Engine_MainLogView_LogResult_Temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_Engine_MainLogView_LogUserDefinedData_General {
            get {
                return ((bool)(this["TDP_Engine_MainLogView_LogUserDefinedData_General"]));
            }
            set {
                this["TDP_Engine_MainLogView_LogUserDefinedData_General"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TDP_Engine_MainLogView_PromptForFailResult {
            get {
                return ((bool)(this["TDP_Engine_MainLogView_PromptForFailResult"]));
            }
            set {
                this["TDP_Engine_MainLogView_PromptForFailResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TDP_EngineLogLogView_TitleWidth {
            get {
                return ((int)(this["TDP_EngineLogLogView_TitleWidth"]));
            }
            set {
                this["TDP_EngineLogLogView_TitleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int TDP_EngineStatusLogView_InfoWindowHeight {
            get {
                return ((int)(this["TDP_EngineStatusLogView_InfoWindowHeight"]));
            }
            set {
                this["TDP_EngineStatusLogView_InfoWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TDP_EngineStatusLogView_PassFailHistoryTitleWidth {
            get {
                return ((int)(this["TDP_EngineStatusLogView_PassFailHistoryTitleWidth"]));
            }
            set {
                this["TDP_EngineStatusLogView_PassFailHistoryTitleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("260")]
        public int TDP_EngineStatusLogView_PassFailHistoryWindowHeight {
            get {
                return ((int)(this["TDP_EngineStatusLogView_PassFailHistoryWindowHeight"]));
            }
            set {
                this["TDP_EngineStatusLogView_PassFailHistoryWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TDP_SequenceExecutor_LastExecutedSequence {
            get {
                return ((string)(this["TDP_SequenceExecutor_LastExecutedSequence"]));
            }
            set {
                this["TDP_SequenceExecutor_LastExecutedSequence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TDP_Engine_DeleteRawReportFile {
            get {
                return ((bool)(this["TDP_Engine_DeleteRawReportFile"]));
            }
            set {
                this["TDP_Engine_DeleteRawReportFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("550")]
        public int TDP_MainLogView_ListViewResultAreaHeight {
            get {
                return ((int)(this["TDP_MainLogView_ListViewResultAreaHeight"]));
            }
            set {
                this["TDP_MainLogView_ListViewResultAreaHeight"] = value;
            }
        }
    }
}
