//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestManager.Extern.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestManager.Extern.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Graph {
            get {
                object obj = ResourceManager.GetObject("Graph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 EngineMode 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_EngineMode {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_EngineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_ExecutionStatus_Error {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_ExecutionStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executed 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_ExecutionStatus_Executed {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_ExecutionStatus_Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_ExecutionStatus_Failed {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_ExecutionStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_ExecutionStatus_OK {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_ExecutionStatus_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passed 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_ExecutionStatus_Passed {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_ExecutionStatus_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skipped 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_ExecutionStatus_Skipped {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_ExecutionStatus_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is a failed test result ouput.
        ///
        ///Click &quot;OK&quot; to continue testing. 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_MainLogView_PromptForFailTestMessage {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_MainLogView_PromptForFailTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_Pause {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_Resume {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_Start {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_Stop {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load test sequence failed. 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_TdpTestSequence_LoadSequenceFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TdpTestSequence_LoadSequenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save TDP test sequence failed. 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_TdpTestSequence_SaveSequenceFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TdpTestSequence_SaveSequenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create case instance failed: 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_TestCase_CreateCaseInstanceFailed {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_CreateCaseInstanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get case limits error. 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_TestCase_GetLimitsError {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_GetLimitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get case parameters error. 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_TestCase_GetParametersError {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_GetParametersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set case limits error. 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_TestCase_SetCaseLimitsError {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_SetCaseLimitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set case parameters error. 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_TestCase_SetCaseParametersError {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_SetCaseParametersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TDP library file not found: 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_TestCase_TdplNotFound {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_TdplNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current TDP L version({0}) not compitible with the test case({1}).
        ///TSPL: {2}
        ///Case: {3}
        ///
        ///To ensure the conformance, you must re-create the sequence and configurate the parameters / limits. 的本地化字符串。
        /// </summary>
        internal static string LNG_TDP_Engine_TestCase_VersionNotCompitiableWarning {
            get {
                return ResourceManager.GetString("LNG_TDP_Engine_TestCase_VersionNotCompitiableWarning", resourceCulture);
            }
        }
    }
}
